VERSION = "v0.2.3"

Settings_Format = {
    "Golden Bugs Shuffled": "Yes/No",
    "Sky Chracters Shuffled": "Yes/No",
    "NPC Items Shuffled": "Yes/No",
    "Shop Items Shuffled": "Yes/No",
    "Hidden Skills Shuffled": "Yes/No",
    "Poes Shuffled": "Yes/No",
    "Heart Pieces Shuffled": "Yes/No",
    "Overworld Shuffled": "Yes/No",
    "Dungeons Shuffled": "Yes/No",
    "Small Key Settings": "Start With/Vanilla/Own Dungeon/Any Dungeon/Anywhere",
    "Big Key Settings": "Start With/Vanilla/Own Dungeon/Any Dungeon/Anywhere",
    "Map and Compass Settings": "Start With/Vanilla/Own Dungeon/Any Dungeon/Anywhere",
    "Dungeon Rewards Progression": "Yes/No",
    "Small keys on Bosses": "Yes/No",
    "Logic Settings": "Glitchless/Glitched/No Logic",
    "Castle Requirements": "Open/Fused Shadows/Mirror Shards/All Dungeons/Vanilla",
    "Palace of Twilight Requirements": "Open/Fused Shadows/Mirror Shards/Vanilla",
    "Faron Woods Logic": "Open/Closed",
    "Open Map": "Yes/No",
    "Increase Wallet": "Yes/No",
    "Transform Anywhere": "Yes/No",
    "Bonks do Damage": "Yes/No",
    "Trap Frequency": "No Traps/Few/Many/Mayhem/Nightmare",
    "Damage Magnification": "Vanilla/Double/Triple/Quadruple/Ohko",
    "Lakebed Entrance Requirements": "Yes/No",
    "Arbiters Grounds Entrance Requirements": "Yes/No",
    "Snowpeak Entrance Requirements": "Yes/No",
    "City in the Sky Entrance Requirements": "Yes/No",
    "Goron Mines Entrance Requirements": "Open/No Wrestling/Closed",
    "Temple of Time Entrance Requirements": "Open/Open Grove/Closed",
    "Early Shadow Crystal": "Yes/No",
    "Skip Prologue": "Yes",
    "Faron Twilight Cleared": "Yes",
    "Eldin Twilight Cleared": "Yes",
    "Lanayru Twilight Cleared": "Yes",
    "Skip MDH": "Yes",
    "Open Door of Time": "Yes",
}
